language: python
include:
  - python: "3.4"
  - python: "3.5"
  - python: "3.6"
  - python: "3.7"
    dist: xenial
    sudo: required
allow_failures:
  - python: "nightly"

# command to install dependencies
install:
  - pip install pytest mock
  - pip install kodi-addon-checker; fi

# command to run tests
script:
  - kodi-addon-checker --branch=leia  -- service.notrobro/; fi
  - py.test -v

jobs:
  include:
    - python: "2.7"
      dist: xenial
      sudo: required
  allow_failures:
    - python: "nightly"
   install:
      - pip install pytest mock
   script: py.test -v
